version: "3.9"
services:
  elasticsearch:
    image: elasticsearch:7.17.2 # 8.3.1 # 7.17.2
    deploy:
      resources:
        limits:
          memory: 2048M
    environment:
      discovery.type: single-node
      ELASTIC_PASSWORD: elastic-pasaword #username is `elastic`
      xpack.security.enabled: "true"
      xpack.security.sameSiteCookies: "None"
      xpack.license.self_generated.type: basic
    volumes:
      - ./elasticsearch:/usr/share/elasticsearch/data
    ports:
      - 9200:9200

  kibana:
    image: kibana:7.17.2 # 8.3.1 # 7.17.2
    deploy:
      resources: 
        limits:
          memory: 2048M
    environment:
      ELASTICSEARCH_USERNAME: "elastic" 
      ELASTICSEARCH_PASSWORD: "elastic-pasaword" 
      ELASTICSEARCH_HOSTS: "http://elasticsearch:9200"
    ports:
      - 5601:5601
    depends_on:
      - elasticsearch
